# Generated by Django 3.0.6 on 2020-05-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='steps',
            field=models.CharField(max_length=60),
        ),
    ]
