# Generated by Django 3.0.6 on 2020-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0004_auto_20200510_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='steps',
        ),
        migrations.AddField(
            model_name='workflow',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='steps', to='workflowapp.step'),
        ),
    ]
