# Generated by Django 3.0.6 on 2020-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0012_auto_20200511_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='steps',
            field=models.ManyToManyField(blank=True, to='workflowapp.step'),
        ),
    ]
