# Generated by Django 3.0.6 on 2020-05-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0014_auto_20200511_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='steps',
            field=models.ManyToManyField(blank=True, to='workflowapp.step'),
        ),
    ]
